package com.swen.comix.controller;

public enum Command {
    GUEST,
    SIGNIN,
    SIGNINPASSWORD,
    SIGNUP,
    SIGNUPPASSWORD,
    BROWSEDATABASE,
    BROWSEOTHERPC,
    PCRESULT,
    SIGNEDINUSER,
    SIGNINCOMPLETE,
    SEARCHPC,
    ADDTOPC,
    REMOVEFROMPC,
    EDITMARKSELECTION,
    UNDO,
    REDO,
    ERROR,
    NEWACCERROR,
    CLOSING
}
