package com.swen.comix.controller;

import com.swen.comix.model.SearchByDescription;

public enum Command {
    GUEST,
    SIGNIN,
    SIGNINPASSWORD,
    SIGNUP,
    SIGNUPPASSWORD,
    SEARCHDATABASE,
    BROWSEOTHERCOLLECTION,
    OTHERCOLLECTIONRESULT,
    SIGNEDINUSER,
    SIGNINCOMPLETE,
    SEARCHCOLLECTION,
    SEARCHTYPEDATABASE,
    SEARCHTYPECOLLECTION,
    ADDTOCOLLECTION,
    REMOVEFROMCOLLECTION,
    EDITMARKSELECTION,
    UNDO,
    REDO,
    IMPORTEXPORT,
    ERROR,
    NEWACCOUNTERROR,
    CLOSING
}
